spring:
  application:
    name: puma-printables-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/puma_printables}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_STARTTLS:false}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    mail:
      enabled: false
    db:
      enabled: true

logging:
  level:
    root: INFO
    "org.hibernate.SQL": DEBUG
    "org.springframework.security": INFO

puma:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-in-prod}
      expiry-minutes: ${JWT_EXPIRY_MINUTES:60}
  notifications:
    enabled: ${PUMA_NOTIFICATIONS_ENABLED:true}
    from-address: ${PUMA_NOTIFICATIONS_FROM:notifications@pumaprintables.local}
    copy-approvers-on-creation: ${PUMA_NOTIFY_APPROVERS_ON_CREATION:true}
